swagger: '2.0'
info:
  version: 1.0.0
  title: Yimba-Design
  description: The Yimba Design Service features the methods that are available for you to interact with all design based elements of the Yimba Service. Within this service you will find methods for listing all available designs within your card program.
host: design.yimbatech.com
schemes:
  - https
paths:
  /:
    get:
      produces:
        - application/json
      parameters:
        - name: x-client-access-token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: 200 response
          schema:
            type: object
            properties:
              count:
                type: number
              designs:
                type: object
                properties:
                  url:
                    type: string
                  created:
                    type: string
                  updated:
                    type: string
                  catagory:
                    type: string
                  design_identifier:
                    type: string
          examples:
            Example Response:
              count: 2
              designs:
                - url: 'https://yimba.s3.eu-west-2.amazonaws.com/Yimba+images/MEDIA/CARTOONS/cartoons1.png'
                  created: '2019-10-15 10:23:53.000000'
                  updated: '2019-10-15 10:23:53.000000'
                  catagory: cartoons
                  design_identifier: 1d428642-73ca-460a-9871-0689cb39d80e
                - url: 'https://yimba.s3.eu-west-2.amazonaws.com/Yimba+images/MEDIA/CARTOONS/cartoons2.jpg'
                  created: '2019-10-15 10:23:53.000000'
                  updated: '2019-10-15 10:23:53.000000'
                  catagory: cartoons
                  design_identifier: c9fb0918-aeaa-4bd4-96c8-e018813f4116
      security:
        - jwt-rsa-custom-authorizer: []
      summary: Get Available Designs
      description: The GET operation at the root of the design service will return all available card designs to you based on your card programme. Your **ClientID** is tied to your available card designs. You may have been issued multiple **ClientID's** by Yimba depending on your issuing status and programme.
      tags:
        - Base Design Service
  /category:
    get:
      produces:
        - application/json
      parameters:
        - name: x-client-access-token
          in: header
          required: true
          type: string
      responses:
        '200':
          description: 200 response
          examples:
            Example Response:
              categories:
                - code: media
                  title: Media
                  designs: []
                  subtitle: Pay with images from your favourite film or TV show
                  description: Pay with images from your favourite film or TV show
                  design_count: 0
                  parent_catagory: null
                - code: 'sports '
                  title: 'Sports '
                  designs: []
                  subtitle: Show your support for your team
                  description: Show your support for your team
                  design_count: 0
                  parent_catagory: null
          schema:
            type: object
            properties:
              categories:
                type: object
                properties:
                  code:
                    type: string
                  title:
                    type: string
                  designs:
                    type: object
                    properties:
                      url:
                        type: string
                      created:
                        type: string
                      updated:
                        type: string
                      catagory:
                        type: string
                      parent_catagory:
                        type: string
                      design_identifier:
                        type: string
                  subtitle:
                    type: string
                  description:
                    type: string
                  design_count:
                    type: number
                  parent_catagory:
                    type: string
      security:
        - jwt-rsa-custom-authorizer: []
      description: The GET operation at the category endpoint will return a list of available design categories to you based on your card programme. Your **ClientID** is tied to your available card designs. You may have been issued multiple **ClientID's** by Yimba depending on your issuing status and programme.
      summary: Get Available Designs By Category
      tags:
        - Designs By Category
  /imageurl:
    get:
      produces:
        - application/json
      parameters:
        - name: design_identifier
          in: header
          required: true
          type: string
      responses:
        '200':
          description: 200 response
          schema:
            type: object
            properties:
              imageURL:
                type: string
          examples:
            Example Response:
              imageURL: 'https://yimba.s3.eu-west-2.amazonaws.com/Yimba+images/MEDIA/MARVEL/marvel1.gif'
      security:
        - jwt-rsa-custom-authorizer: []
      description: 'The GET operation at the imageurl endpoint is designed to assist you in obtaining the URL for a given image identifier. As shown below, you need to pass the relevant **design_identifer** and the corresponding image URL will be returned.'
      summary: Get Design URL
      tags:
        - Get Individual Design
securityDefinitions:
  jwt-rsa-custom-authorizer:
    type: apiKey
    name: Authorization
    in: header
    x-amazon-apigateway-authtype: custom
definitions: {}
